# Generated by Django 4.0 on 2022-01-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_interestscheme_max_interest_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestbreakpoint',
            options={'ordering': ['balance_breakpoint']},
        ),
        migrations.RemoveField(
            model_name='interestbreakpoint',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='account',
            name='upcoming_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='interestbreakpoint',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interestbreakpoint',
            name='balance_breakpoint',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interestbreakpoint',
            name='interest_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakpoints', to='accounts.interestscheme'),
        ),
    ]
