# Generated by Django 4.0 on 2022-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_interestbreakpoint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='upcoming_interest',
        ),
        migrations.AddField(
            model_name='account',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='historical_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interestbreakpoint',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
