# Generated by Django 4.0 on 2022-02-12 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_upcoming_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_interest_accrued',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
