# Generated by Django 4.0 on 2022-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_last_interest_accrued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
