version: '3.2'

volumes:
  dadbank_postgres: {}
  # node_stuff: {}

services:

  django:
    build: ./backend
    volumes:
      - ./backend:/app
    ports: 
      - "8000:8000"
    depends_on:
      - django_postgres
    env_file:
      - "./backend/.docker.env"

  django_postgres:
    image: postgres:14.1
    volumes:
      - dadbank_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dadbank_django
    ports:
      - "5432:5432"
    # restart: always
    
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
