# Generated by Django 4.0 on 2021-12-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_transaction_transaction_type_interestscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestscheme',
            name='max_interest_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
